version: 2

sources:
  - name: dbsales_khd7
    schema: public
    tables:
      - name: commodities
        description: "Tabela que contem dados historicos de commodities"
        columns:
          - name: Date
            description: "Data da observacao"
          - name: Close
            description: "Preco de fechamento da commodity"
          - name: simbolo
            description: "Simbolo da commodity"

      - name: movimentacao_commodities
        description: "Tabela transacional com movimentacoes de commodities"
        columns:
          - name: date
            description: "Data da transacao no formato AAAA-MM-DD"
          - name: symbol
            description: "Simbolo da commodity"
          - name: action
            description: "Tipo da transacao (buy/sell)"
          - name: quantity
            description: "Quantidade transacionada"
